// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using NSwag.CodeGeneration.TypeScript.Infrastructure;

namespace NSwag.CodeGeneration.TypeScript.Templates
{
    using NJsonSchema;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    internal partial class JQueryPromisesClientTemplate : JQueryPromisesClientTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n");
            
            #line 5 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
if(Model.HasOperations){
            
            #line default
            #line hidden
            
            #line 6 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
if(Model.GenerateClientInterfaces){
            
            #line default
            #line hidden
            this.Write("export interface I");
            
            #line 7 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Class));
            
            #line default
            #line hidden
            this.Write(" {\r\n");
            
            #line 8 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
foreach(var operation in Model.Operations){
            
            #line default
            #line hidden
            
            #line 9 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
if(operation.HasDocumentation){
            
            #line default
            #line hidden
            this.Write("    /**\r\n");
            
            #line 10 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
if(operation.HasSummary){
            
            #line default
            #line hidden
            this.Write("     * ");
            
            #line 10 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.Summary));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 11 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 11 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
foreach(var parameter in operation.Parameters){
            
            #line default
            #line hidden
            
            #line 12 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
if(parameter.HasDescriptionOrIsOptional){
            
            #line default
            #line hidden
            this.Write("     * @");
            
            #line 12 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.VariableName));
            
            #line default
            #line hidden
            
            #line 12 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
if(parameter.IsOptional){
            
            #line default
            #line hidden
            this.Write(" (optional)");
            
            #line 12 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 12 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Description ?? ""));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 13 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 13 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 13 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
if(operation.HasResultDescription){
            
            #line default
            #line hidden
            this.Write("     * @return ");
            
            #line 13 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.ResultDescription));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 14 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 14 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
if(operation.IsDeprecated){
            
            #line default
            #line hidden
            this.Write("     * @deprecated\r\n");
            
            #line 15 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("     */\r\n");
            
            #line 16 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 16 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.OperationNameLower));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 16 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
foreach(var parameter in operation.Parameters){
            
            #line default
            #line hidden
            
            #line 16 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.VariableName));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 16 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Type));
            
            #line default
            #line hidden
            
            #line 16 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
if(!parameter.IsLast){
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 16 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 16 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("): ");
            
            #line 16 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.PromiseType));
            
            #line default
            #line hidden
            this.Write("<");
            
            #line 16 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.ResultType));
            
            #line default
            #line hidden
            this.Write(">;\r\n");
            
            #line 17 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 18 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\nexport class ");
            
            #line 20 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Class));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 20 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
if(Model.HasClientBaseClass){
            
            #line default
            #line hidden
            this.Write("extends ");
            
            #line 20 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ClientBaseClass));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 20 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 20 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
if(Model.GenerateClientInterfaces){
            
            #line default
            #line hidden
            this.Write("implements I");
            
            #line 20 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Class));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 20 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("{\r\n    baseUrl: string = undefined; \r\n    beforeSend: any = undefined; \r\n    prot" +
                    "ected jsonParseReviver: ");
            
            #line 23 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
if(Model.SupportsStrictNullChecks){
            
            #line default
            #line hidden
            this.Write("((key: string, value: any) => any) | undefined");
            
            #line 23 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
}else{
            
            #line default
            #line hidden
            this.Write("(key: string, value: any) => any");
            
            #line 23 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write(" = undefined;\r\n\r\n    constructor(baseUrl?: string) {\r\n");
            
            #line 26 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
if(Model.HasClientBaseClass){
            
            #line default
            #line hidden
            this.Write("        super();\r\n");
            
            #line 28 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("        this.baseUrl = baseUrl !== undefined ? baseUrl : \"");
            
            #line 29 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.BaseUrl));
            
            #line default
            #line hidden
            this.Write("\"; \r\n    }\r\n");
            
            #line 31 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
if(Model.HasExtensionClass && !Model.HasClientBaseClass){
            
            #line default
            #line hidden
            
            #line 32 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
  if(Model.UseTransformOptionsMethod){
            
            #line default
            #line hidden
            this.Write("\r\n    protected transformOptions(options: any) {\r\n        return options; \r\n    }" +
                    "\r\n");
            
            #line 37 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
  }
            
            #line default
            #line hidden
            
            #line 38 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
  if(Model.UseTransformResultMethod){
            
            #line default
            #line hidden
            this.Write("\r\n    protected transformResult(url: string, xhr: any, processor: (xhr: any) => a" +
                    "ny) {\r\n        return processor(xhr);\r\n    }\r\n");
            
            #line 43 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
  }
            
            #line default
            #line hidden
            
            #line 44 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 45 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
foreach(var operation in Model.Operations){
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 47 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
if(operation.HasDocumentation){
            
            #line default
            #line hidden
            this.Write("    /**\r\n");
            
            #line 48 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
if(operation.HasSummary){
            
            #line default
            #line hidden
            this.Write("     * ");
            
            #line 48 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.Summary));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 49 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 49 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
foreach(var parameter in operation.Parameters){
            
            #line default
            #line hidden
            
            #line 50 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
if(parameter.HasDescriptionOrIsOptional){
            
            #line default
            #line hidden
            this.Write("     * @");
            
            #line 50 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.VariableName));
            
            #line default
            #line hidden
            
            #line 50 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
if(parameter.IsOptional){
            
            #line default
            #line hidden
            this.Write(" (optional)");
            
            #line 50 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 50 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Description ?? ""));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 51 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 51 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 51 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
if(operation.HasResultDescription){
            
            #line default
            #line hidden
            this.Write("     * @return ");
            
            #line 51 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.ResultDescription));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 52 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 52 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
if(operation.IsDeprecated){
            
            #line default
            #line hidden
            this.Write("     * @deprecated\r\n");
            
            #line 53 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("     */\r\n");
            
            #line 54 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 54 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.OperationNameLower));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 54 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
foreach(var parameter in operation.Parameters){
            
            #line default
            #line hidden
            
            #line 54 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.VariableName));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 54 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Type));
            
            #line default
            #line hidden
            
            #line 54 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
if(!parameter.IsLast){
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 54 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 54 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("): ");
            
            #line 54 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.PromiseType));
            
            #line default
            #line hidden
            this.Write("<");
            
            #line 54 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.ResultType));
            
            #line default
            #line hidden
            this.Write("> {\r\n        return ");
            
            #line 55 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.PromiseConstructor));
            
            #line default
            #line hidden
            this.Write("<");
            
            #line 55 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.ResultType));
            
            #line default
            #line hidden
            this.Write(">((resolve, reject) => {\r\n            this.");
            
            #line 56 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.OperationNameLower));
            
            #line default
            #line hidden
            this.Write("WithCallbacks(");
            
            #line 56 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
foreach(var parameter in operation.Parameters){
            
            #line default
            #line hidden
            
            #line 56 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.VariableName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 56 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("(result) => resolve(result), (exception, reason) => reject(exception));\r\n        " +
                    "});\r\n    }\r\n    \r\n    private ");
            
            #line 60 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.OperationNameLower));
            
            #line default
            #line hidden
            this.Write("WithCallbacks(");
            
            #line 60 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
foreach(var parameter in operation.Parameters){
            
            #line default
            #line hidden
            
            #line 60 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.VariableName));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 60 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Type));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 60 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("onSuccess?: (result: ");
            
            #line 60 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.ResultType));
            
            #line default
            #line hidden
            this.Write(") => void, onFail?: (exception: ");
            
            #line 60 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.ExceptionType));
            
            #line default
            #line hidden
            this.Write(", reason: string) => void) {\r\n        ");
            
            #line 61 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeScriptTemplatePartGenerator.RenderRequestUrlCode(operation, 2)));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n        ");
            
            #line 63 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeScriptTemplatePartGenerator.RenderRequestBodyCode(operation, 2)));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n        jQuery.ajax(");
            
            #line 65 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
if(Model.UseTransformOptionsMethod){
            
            #line default
            #line hidden
            this.Write("this.transformOptions(");
            
            #line 65 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("{\r\n            url: url_,\r\n            beforeSend: this.beforeSend,\r\n            " +
                    "type: \"");
            
            #line 68 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.HttpMethodLower));
            
            #line default
            #line hidden
            this.Write("\",\r\n            data: content_,\r\n");
            
            #line 70 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
  if(operation.HasFormParameters){
            
            #line default
            #line hidden
            this.Write("            mimeType: \"multipart/form-data\",\r\n            contentType: false,\r\n");
            
            #line 73 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
  }else{
            
            #line default
            #line hidden
            this.Write("            dataType: \"text\",\r\n");
            
            #line 75 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
  }
            
            #line default
            #line hidden
            this.Write("            headers: {\r\n");
            
            #line 77 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
foreach(var parameter in operation.HeaderParameters){
            
            #line default
            #line hidden
            this.Write("                \"");
            
            #line 78 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            
            #line default
            #line hidden
            this.Write("\": ");
            
            #line 78 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.VariableName));
            
            #line default
            #line hidden
            this.Write(", \r\n");
            
            #line 79 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("                \"Content-Type\": \"");
            
            #line 79 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.Consumes));
            
            #line default
            #line hidden
            this.Write("; charset=UTF-8\",\r\n\t\t\t\t\"Accept\": \"");
            
            #line 80 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.Produces));
            
            #line default
            #line hidden
            this.Write("; charset=UTF-8\"\r\n            }\r\n        }");
            
            #line 82 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
if(Model.UseTransformOptionsMethod){
            
            #line default
            #line hidden
            this.Write(")");
            
            #line 82 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write(").done((data, textStatus, xhr) => {\r\n            this.process");
            
            #line 83 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.OperationNameUpper));
            
            #line default
            #line hidden
            this.Write("WithCallbacks(url_, xhr, onSuccess, onFail);\r\n        }).fail((xhr) => {\r\n       " +
                    "     this.process");
            
            #line 85 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.OperationNameUpper));
            
            #line default
            #line hidden
            this.Write("WithCallbacks(url_, xhr, onSuccess, onFail);\r\n        });\r\n    }\r\n\r\n    private p" +
                    "rocess");
            
            #line 89 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.OperationNameUpper));
            
            #line default
            #line hidden
            this.Write("WithCallbacks(url: string, xhr: any, onSuccess?: any, onFail?: any): void {\r\n    " +
                    "    try {\r\n");
            
            #line 91 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
if(Model.UseTransformResultMethod){
            
            #line default
            #line hidden
            this.Write("            let result = this.transformResult(url, xhr, (xhr) => this.process");
            
            #line 92 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.OperationNameUpper));
            
            #line default
            #line hidden
            this.Write("(xhr));\r\n");
            
            #line 93 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
}else{
            
            #line default
            #line hidden
            this.Write("            let result = this.process");
            
            #line 94 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.OperationNameUpper));
            
            #line default
            #line hidden
            this.Write("(xhr);\r\n");
            
            #line 95 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("            if (onSuccess !== undefined)\r\n                onSuccess(result);\r\n   " +
                    "     } catch (e) {\r\n            if (onFail !== undefined)\r\n                onFai" +
                    "l(e, \"http_service_exception\");\r\n        }\r\n    }\r\n\r\n    protected process");
            
            #line 104 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.OperationNameUpper));
            
            #line default
            #line hidden
            this.Write("(xhr: any): ");
            
            #line 104 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.ResultType));
            
            #line default
            #line hidden
            this.Write(" {\r\n        const responseText = xhr.responseText; \r\n        const status = xhr.s" +
                    "tatus; \r\n\r\n        ");
            
            #line 108 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeScriptTemplatePartGenerator.RenderProcessResponseCode(operation, 2)));
            
            #line default
            #line hidden
            this.Write("\r\n    }\r\n");
            
            #line 110 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n    ");
            
            #line 112 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeScriptTemplatePartGenerator.RenderClientMethodsCode(Model, 1)));
            
            #line default
            #line hidden
            this.Write("\r\n}\r\n");
            
            #line 114 "C:\Data\NSwag\src\NSwag.CodeGeneration.TypeScript\Templates\JQueryPromisesClientTemplate.tt"
}
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    internal class JQueryPromisesClientTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::NSwag.CodeGeneration.TypeScript.Infrastructure.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::NSwag.CodeGeneration.TypeScript.Infrastructure.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            CompilerError error = new global::NSwag.CodeGeneration.TypeScript.Infrastructure.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            CompilerError error = new global::NSwag.CodeGeneration.TypeScript.Infrastructure.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
